### ISSUE TITLE
Dependency from private Verdaccio instance is required

### ISSUE THREAD

**Issue by jimfilippou** [Quintessential-SFT/Covid-19-API#1]
### Problem
"40.68.159.229" verdaccio instance requires auth to pull the package "apidoc" which is not required to run the server.
 
`yarn install`

```
yarn install v1.19.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "http://40.68.159.229/apidoc-core/-/apidoc-core-0.11.1.tgz: Request failed \"401 Unauthorized\"".
```

**Comment by jimfilippou** [comment]
#### Proposed solution
Either remove it completely & move it to a CD pipeline on your end, or publish the package.

**Comment by kkopanidis** [comment]
Once again betrayed by the registry. Removing the yarn.lock completely
