### ISSUE TITLE
Example missing for custom endpoint

### ISSUE THREAD

**Issue by platisd** [Quintessential-SFT/Covid-19-API#3]
Could you please document what is the expected format of `dateString` at the `custom` endpoint?

I am trying the `MM-DD-YYYY` one (e.g. `https://covid-api.quintessential.gr/data/custom?country=greece&date=03-15-2020`) but I get an error.

Not a JavaScript guy either so I can't figure out where the problem is. Seems like it should have worked.

**Comment by kkopanidis** [comment]
@platisd fixed on the published API and updated the repo

**Comment by platisd** [comment]
I saw your fix, but still don't understand what the intended format should be! :smile:

Can you please formulate a sample `GET` request?

**Comment by kkopanidis** [comment]
@platisd Sorry for the delay, the exact URL that you have in your issue description is correct. The general idea is that you add the country, and the date in MM-DD-YYYY. Do you have a specific example in mind?

**Comment by platisd** [comment]
Earlier I was trying out the `GET` request I initially mentioned (i.e. `https://covid-api.quintessential.gr/data/custom?country=greece&date=03-15-2020`) and it was not working. Now this particular one seems to be fine, however any other date that I am trying seems induce errors, e.g. for the 12th of March: `https://covid-api.quintessential.gr/data/custom?country=greece&date=03-12-2020`.

Is this intentional or a bug?

My goal is to create a **Corona lamp** based on my [Code review lamp](https://github.com/platisd/code-review-lamp), so I want to get the new infections for each day for the past two weeks and shine accordingly.

**Comment by kkopanidis** [comment]
I have a feeling  that there no data for greece and for that date, but I'll confirm and get back to you. If that's the case it should at least send a 404 error. Perhaps we could also include an endpoint that would give you the first date that there was data.

**Comment by platisd** [comment]
Oh I see. I was under the impression there were data daily, but yeah, having the same error for malformed requests and the absence of information can make things ambiguous. :grin:

**Comment by kkopanidis** [comment]
Soooo, I was wrong as it seems. The error was an empty line issue in the csv, which caused the country name check to crash. It has been resolved, and the API is being updated at this moment

**Comment by platisd** [comment]
Looks good now, thanks! :)

**Comment by platisd** [comment]
The [Corona Lamp](https://platis.solutions/blog/2020/03/24/corona-lamp/) is ready now thanks to your work! :+1: 
The code that uses your API to fetch data can be found [here](https://github.com/platisd/code-review-lamp/tree/master/firmware/corona_lamp).
